import {test} from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {PGlite} from '@electric-sql/pglite';
test('calculated resources, consumables and shops',async()=>{const db=new PGlite();await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;create schema auth;create table auth.users(id uuid primary key,email text,encrypted_password text);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema public,auth to authenticated;grant execute on function auth.uid() to authenticated;`);
for(const f of ['001_core.sql','002_accounts.sql','20260911201143_resources_consumables_shops.sql']){let sql=await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8');await db.exec(sql.replace('create extension if not exists pgcrypto;','').replace('alter publication supabase_realtime add table public.campaign_events;',''));}
const ids=(await db.query<{id:string}>('insert into auth.users(id) values(gen_random_uuid()),(gen_random_uuid()),(gen_random_uuid()) returning id')).rows.map(r=>r.id);const [master,player,other]=ids;const c=(await db.query<{id:string}>("select bootstrap_campaign($1,'mestre','a@a.invalid','cipher') id",[master])).rows[0].id;
const make=async(u:string,n:string)=>(await db.query<{id:string}>("select provision_player($1,$2,$3,$4,'cipher','{\"name\":\"Kael\",\"life\":60,\"money\":100}',null) id",[c,u,n,n+'@a.invalid'])).rows[0].id;const ch=await make(player,'arthur'),ch2=await make(other,'bia');
const attrs=(await db.query<{id:string,name:string}>('select id,name from attributes')).rows;const vigor=attrs.find(a=>a.name==='Vigor')!.id,power=attrs.find(a=>a.name==='Poder')!.id;
async function as(u:string){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[u]);await db.exec('set role authenticated');}
const action=(op:string,d:object)=>db.query('select game_action($1,$2,$3::jsonb)',[c,op,JSON.stringify(d)]);const cmd=(op:string,d:object)=>db.query('select game_command($1,$2,$3::jsonb)',[c,op,JSON.stringify(d)]);const life=async()=>(await db.query<{current:number,maximum:number}>("select current,maximum from character_resources where character_id=$1 and key='life'",[ch])).rows[0];
await as(master);await cmd('attribute_value',{character_id:ch,attribute_id:vigor,value:12});await cmd('attribute_value',{character_id:ch,attribute_id:power,value:8});assert.deepEqual(await life(),{current:0,maximum:60});await cmd('resource',{character_id:ch,key:'life',delta:42});await action('resource_config',{character_id:ch,key:'life',inherit_rule:false,automatic:true,attribute_id:vigor,multiplier:4,manual_maximum:60});assert.deepEqual(await life(),{current:42,maximum:48});await cmd('attribute_value',{character_id:ch,attribute_id:vigor,value:5});assert.deepEqual(await life(),{current:20,maximum:20});await cmd('attribute_value',{character_id:ch,attribute_id:vigor,value:12});assert.deepEqual(await life(),{current:20,maximum:48});await action('campaign_rule',{key:'life',automatic:true,attribute_id:vigor,multiplier:6});assert.equal((await life()).maximum,48);await action('resource_config',{character_id:ch,key:'life',inherit_rule:true,automatic:false,attribute_id:null,multiplier:1,manual_maximum:60});assert.equal((await life()).maximum,72);await action('resource_config',{character_id:ch,key:'life',inherit_rule:false,automatic:false,attribute_id:null,multiplier:1,manual_maximum:60});assert.equal((await life()).maximum,60);await cmd('resource',{character_id:ch,key:'life',delta:22});
await cmd('item',{name:'Poção',description:'Cura'});const item=(await db.query<{id:string}>('select id from items')).rows[0].id;await action('item_config',{item_id:item,kind:'consumable',effects:{life:20,mana:25}});await cmd('inventory',{character_id:ch,item_id:item,quantity:3});const inv=(await db.query<{id:string}>('select id from character_items')).rows[0].id;await as(player);const use={character_id:ch,inventory_id:inv,request_id:crypto.randomUUID()};await action('consume',use);assert.deepEqual(await life(),{current:60,maximum:60});await action('consume',use);assert.equal((await db.query<{quantity:number}>('select quantity from character_items')).rows[0].quantity,2);await assert.rejects(action('consume',{...use,character_id:ch2,request_id:crypto.randomUUID()}));await assert.rejects(cmd('resource',{character_id:ch,key:'life',delta:20}));await assert.rejects(action('campaign_rule',{key:'life',automatic:true,attribute_id:vigor,multiplier:99}));
await as(master);await action('shop',{name:'Boticário'});const shop=(await db.query<{id:string}>('select id from shops')).rows[0].id;await action('product',{shop_id:shop,item_id:item,name:'Poção',price:30,stock:1});const product=(await db.query<{id:string}>('select id from shop_products')).rows[0].id;await as(player);const buy={character_id:ch,product_id:product,request_id:crypto.randomUUID()};await action('purchase',buy);await action('purchase',buy);assert.equal((await db.query<{money:number}>('select money from characters where id=$1',[ch])).rows[0].money,70);await assert.rejects(action('purchase',{...buy,request_id:crypto.randomUUID()}));assert.equal((await db.query<{stock:number}>('select stock from shop_products')).rows[0].stock,0);await assert.rejects(db.query('update character_resources set current=maximum'));await db.close();});
